export const translate =  (key, lanauge) => {
  const english = {
    // General
    "Switch Language": "Switch Language",
    "Comparative Analytics": "Comparative Analytics",
    "Select Books": "Select Books",
    "Select Months": "Select Months",
    "Global Annual": "Global Annual",
    "Book": "Book",
    "Initial Balance": "Initial Balance",
    "Total Receipts": "Total Receipts",
    "Total Disbursements": "Total Disbursements",
    "Final Treasury": "Final Treasury",
    "Financial Overview": "Financial Overview",
    "Receipts Breakdown": "Receipts Breakdown",
    "Disbursements Breakdown": "Disbursements Breakdown",
    "Monthly Totals": "Monthly Totals",
    "Monthly Transaction Heatmap": "Monthly Transaction Heatmap",
    "Treasury Evolution Over Time": "Treasury Evolution Over Time",
    "Accumulated Treasury": "Accumulated Treasury",
    "Treasury Balance": "Treasury Balance",
    "Percentage of Treasury vs Receipts": "Percentage of Treasury vs Receipts",
    
    // Dashboard and Navigation
    "Transaction Books": "Transaction Books",
    "Generate Random Summary": "Generate Random Summary",
    "Add New Summary": "Add New Summary",
    "Analytics": "Analytics",
    "Units": "Units",
    "Summary": "Summary",
    "Logout": "Logout",
    "Login": "Login",
    "Register": "Register",
    "Help Center": "Help Center",
    "Privacy Policy": "Privacy Policy",
    "Follow Us": "Follow Us",
    
    // Forms and Buttons
    "Submit": "Submit",
    "Cancel": "Cancel",
    "Select Location": "Select Location",
    "Select Store": "Select Store",
    "Select Duration": "Select Duration",
    "Justification": "Justification",
    "Provision Product": "Provision Product",
    "Request Another Intervention": "Request Another Intervention",
    "Stop Scheduling Interventions": "Stop Scheduling Interventions",
    "Stop Selling Product": "Stop Selling Product",
    "Export as Spreadsheet": "Export as Spreadsheet",
    "Generate Units": "Generate Units",
    "Generate SEPA XML for Expenses": "Generate SEPA XML for Expenses",
    
    // Financial Terms
    "Initial Outflow Amount": "Initial Outflow Amount",
    "Product Purchases": "Product Purchases",
    "Work Payments": "Work Payments",
    "Expenditure Overview": "Expenditure Overview",
    "Most Expensive Products": "Most Expensive Products",
    "Purchase Frequency Heatmap": "Purchase Frequency Heatmap",
    "Product Purchase Trends": "Product Purchase Trends",
    "Initial Inflow Amount": "Initial Inflow Amount",
    "Product Sales": "Product Sales",
    "Work Earnings": "Work Earnings",
    "Revenue Overview": "Revenue Overview",
    "Most Profitable Products": "Most Profitable Products",
    "Sales Heatmap": "Sales Heatmap",
    "Product Sales Trends": "Product Sales Trends",

    // Table Headers
    "Type": "Type",
    "Nature of transaction": "Nature of transaction",
    "Initial Balance": "Initial Balance",
    "Total": "Total",
    "Accumulated Treasury": "Accumulated Treasury",
    "Percentage of Treasury vs Receipts": "Percentage of Treasury vs Receipts",

    // Specific for Units
    "Intervention Location": "Intervention Location",
    "Hours Requested": "Hours Requested",
    "Status": "Status",
    "Actions": "Actions",
    "Duration": "Duration",
    "Units": "Units",
    "Store": "Store",
    "Requested": "Requested",
    "Stop Duration": "Stop Duration",
    "Call": "Call",
    "Email": "Email",
    "Final Amount": "Final Amount",
    "Purchase Date": "Purchase Date",
    "Notes": "Notes",
    "Hourly Rate": "Hourly Rate",
    "Hours Worked": "Hours Worked",
    "Total Earnings": "Total Earnings",
    "Description": "Description",
    "Rate": "Rate",
    "Unit Price": "Unit Price",
    "Total Amount": "Total Amount",
    "Category": "Category",
    "Select Unit Type": "Select Unit Type",
    "Revenues": "Revenues",
    "Expenses": "Expenses",
    "Generate": "Generate",
    "All Categories": "All Categories",
    "All Types": "All Types",
    "Filter by Category": "Filter by Category",
    "Filter by Type": "Filter by Type",
    "Filter by Month": "Filter by Month",
    "Filter by Year": "Filter by Year",
    "January": "January",
    "February": "February",
    "March": "March",
    "April": "April",
    "May": "May",
    "June": "June",
    "July": "July",
    "August": "August",
    "September": "September",
    "October": "October",
    "November": "November",
    "December": "December",
    "Encaissements": "Income",
    "Decaissements": "Expenses"
  };
  
  const french = {
    // General$
    "Switch Language": "Changer de langue",
    "Treasury Evolution Over Time" : "Évolution de la trésorerie à travers le temps",
    "Monthly Transction Heatmap": "Heatmap des transactions mensuelles",
    "Comparative Analytics": "Analyse comparative",
    "Select Books": "Sélectionnez les livres",
    "Select Months": "Sélectionnez les mois",
    "Global Annual": "Annuel global",
    "Book": "Livre",
    "Initial Balance": "Solde initial",
    "Total Receipts": "Encaissements totaux",
    "Total Disbursements": "Décaissements totaux",
    "Final Treasury": "Trésorerie finale",
    "Financial Overview": "Vue d'ensemble financière",
    "Receipts Breakdown": "Répartition des encaissements",
    "Disbursements Breakdown": "Répartition des décaissements",
    "Monthly Totals": "Totaux mensuels",
    "Monthly Transaction Heatmap": "Heatmap des transactions mensuelles",
    "Treasury Evolution Over Time": "Évolution de la trésorerie au fil du temps",
    "Accumulated Treasury": "Trésorerie Accumulée",
    "Treasury Balance": "Solde de Trésorerie",
    "Percentage of Treasury vs Receipts": "Percentage of Treasury vs Encaissements",
    "Percentage of Treasury vs Encaissements": "Pourcentage de (Trésororie vs Encaissements)",
    // Dashboard and Navigation
    "Transaction Books": "Livres de transactions",
    "Generate Random Summary": "Générer un résumé aléatoire",
    "Add New Summary": "Ajouter un nouveau résumé",
    "Analytics": "Analytique",
    "Units": "Unités",
    "Summary": "Résumé",
    "Logout": "Déconnexion",
    "Login": "Connexion",
    "Register": "S'inscrire",
    "Help Center": "Centre d'aide",
    "Privacy Policy": "Politique de confidentialité",
    "Follow Us": "Suivez-nous",
    
    // Forms and Buttons
    "Submit": "Soumettre",
    "Cancel": "Annuler",
    "Select Location": "Sélectionnez l'emplacement",
    "Select Store": "Sélectionnez le magasin",
    "Select Duration": "Sélectionnez la durée",
    "Justification": "Justification",
    "Provision Product": "Approvisionner le produit",
    "Request Another Intervention": "Demander une autre intervention",
    "Stop Scheduling Interventions": "Arrêter de planifier des interventions",
    "Stop Selling Product": "Arrêter de vendre le produit",
    "Export as Spreadsheet": "Exporter en tant que feuille de calcul",
    "Generate Units": "Générer des unités",
    "Generate SEPA XML for Expenses": "Générer un XML SEPA pour les dépenses",
    
    // Financial Terms
    "Initial Outflow Amount": "Montant initial de sortie",
    "Product Purchases": "Achats de produits",
    "Work Payments": "Paiements de travail",
    "Expenditure Overview": "Vue d'ensemble des dépenses",
    "Most Expensive Products": "Produits les plus chers",
    "Purchase Frequency Heatmap": "Heatmap de fréquence d'achat",
    "Product Purchase Trends": "Tendances d'achat de produits",
    "Initial Inflow Amount": "Montant initial d'entrée",
    "Product Sales": "Ventes de produits",
    "Work Earnings": "Gains de travail",
    "Revenue Overview": "Vue d'ensemble des revenus",
    "Most Profitable Products": "Produits les plus rentables",
    "Sales Heatmap": "Heatmap des ventes",
    "Product Sales Trends": "Tendances de vente de produits",

    // Table Headers
    "Type": "Type",
    "Nature of transaction": "Nature de la transaction",
    "Initial Balance": "Solde Initial",
    "Total": "Total",
    "Accumulated Treasury": "Trésorerie Accumulée",
    "Percentage of Treasury vs Receipts": "Percentage of Treasury vs Encaissements",

    // Specific for Units
    "Intervention Location": "Lieu d'intervention",
    "Hours Requested": "Heures demandées",
    "Status": "Statut",
    "Actions": "Actions",
    "Duration": "Durée",
    "Units": "Unités",
    "Store": "Magasin",
    "Requested": "Demandé",
    "Stop Duration": "Durée d'arrêt",
    "Call": "Appel",
    "Email": "Email",
    "Final Amount": "Montant final",
    "Purchase Date": "Date d'achat",
    "Notes": "Remarques",
    "Hourly Rate": "Taux horaire",
    "Hours Worked": "Heures travaillées",
    "Total Earnings": "Gains totaux",
    "Description": "Description",
    "Rate": "Taux",
    "Unit Price": "Prix unitaire",
    "Total Amount": "Montant total",
    "Category": "Catégorie",
    "Select Unit Type": "Sélectionnez le type d'unité",
    "Revenues": "Revenus",
    "Expenses": "Dépenses",
    "Generate": "Générer",
    "All Categories": "Toutes catégories",
    "All Types": "Tous les types",
    "Filter by Category": "Filtrer par catégorie",
    "Filter by Type": "Filtrer par type",
    "Filter by Month": "Filtrer par mois",
    "Filter by Year": "Filtrer par année",
    "January": "Janvier",
    "February": "Février",
    "March": "Mars",
    "April": "Avril",
    "May": "Mai",
    "June": "Juin",
    "July": "Juillet",
    "August": "Août",
    "September": "Septembre",
    "October": "Octobre",
    "November": "Novembre",
    "December": "Décembre",
    "Encaissements": "Encaissements",
    "Decaissements": "Décaissements"
  };

  if(lanauge == 'fr') {
    return french[key];
  }
  
  return english[key]; 
};
