export const actionToDescriptionMap = {
    "fetchItems": "Retrieve a list of all items in the current category.",
    "addItem": "Add a new item to the current category.",
    "updateItem": "Update an existing item in the current category.",
    "deleteItem": "Remove an item from the current category.",
    "validateAccordingToEULawDirective2010": "Ensure compliance with EU Directive 2010/45/EU regarding electronic invoices.",
    "validateAccordingToEULawDirective2013": "Ensure compliance with EU Directive 2013/34/EU on financial statements.",
    "validateAccordingToISO9001": "Ensure compliance with ISO 9001 standards for quality management systems.",
    "validateAccordingToISO45001": "Ensure compliance with ISO 45001 standards for occupational health and safety management.",
    "validateAccordingToISO55000": "Ensure compliance with ISO 55000 standards for asset management.",
    "validateAccordingToISO28000": "Ensure compliance with ISO 28000 standards for supply chain security management.",
    "validateAccordingToIFRS9": "Ensure compliance with IFRS 9 standards for financial instruments.",
    "validateAccordingToIAS1": "Ensure compliance with IAS 1 standards for the presentation of financial statements.",
    "validateAccordingToIAS2": "Ensure compliance with IAS 2 standards for inventories.",
    "validateAccordingToISO31000": "Ensure compliance with ISO 31000 standards for risk management.",
    "validateAccordingToISO19600": "Ensure compliance with ISO 19600 standards for compliance management systems.",
    "validateAccordingToISO27001": "Ensure compliance with ISO 27001 standards for information security management.",
    "validateAccordingToTRIPSAgreement": "Ensure compliance with the TRIPS Agreement for intellectual property rights.",
    "validateAccordingToISO30401": "Ensure compliance with ISO 30401 standards for knowledge management systems.",
    "validateAccordingToISO50001": "Ensure compliance with ISO 50001 standards for energy management systems.",
    "validateAccordingToGDPR": "Ensure compliance with the General Data Protection Regulation (GDPR).",
    "validateAccordingToEUEmploymentLaw": "Ensure compliance with EU employment laws.",
    "validateAccordingToOECDPrinciples": "Ensure compliance with OECD Principles of Corporate Governance.",
    "validateAccordingToContractLaw": "Ensure compliance with relevant contract law requirements.",
    "validateAccordingToSWIFTRegulations": "Ensure compliance with SWIFT standards for financial transactions.",
    "validateAccordingToIMORegulations": "Ensure compliance with International Maritime Organization regulations for shipping.",
    "validateAccordingToPMBOK": "Ensure compliance with PMBOK standards for project management.",
    "validateAccordingToISO30414": "Ensure compliance with ISO 30414 standards for human capital reporting.",
    "validateAccordingToISO21500": "Ensure compliance with ISO 21500 standards for project management guidelines.",
    "validateAccordingToISO10002": "Ensure compliance with ISO 10002 standards for quality management in customer satisfaction.",
    "validateAccordingToISO10004": "Ensure compliance with ISO 10004 standards for monitoring and measuring customer satisfaction.",
    "validateAccordingToISO22301": "Ensure compliance with ISO 22301 standards for business continuity management.",
    "validateAccordingToISO56002": "Ensure compliance with ISO 56002 standards for innovation management.",
    "validateAccordingToGRIStandards": "Ensure compliance with Global Reporting Initiative (GRI) standards for sustainability reporting.",
    "validateAccordingToISO20400": "Ensure compliance with ISO 20400 standards for sustainable procurement.",
    "generateLedgerReport": "Generate a detailed report of all creditor transactions.",
    "generateAgingReport": "Generate a report analyzing outstanding receivables by age.",
    "generateReconciliationReport": "Generate a report comparing internal records with external statements.",
    "generateTransferReport": "Generate a report of all bank transfers executed.",
    "generateInventoryReport": "Generate a report on current inventory levels and valuation.",
    "generateProjectStatusReport": "Generate a detailed report on the current status of all projects.",
    "generateRiskAssessmentReport": "Generate a comprehensive risk assessment report.",
    "generateComplianceAudit": "Generate an audit report assessing compliance with regulatory requirements.",
    "generatePerformanceReviewReport": "Generate a report summarizing employee performance evaluations.",
    "generateCrisisManagementReport": "Generate a report detailing crisis management strategies and responses.",
    "generateKPIReport": "Generate a report on key performance indicators across the organization.",
    "generateSupplyChainReport": "Generate a detailed report on supply chain operations and efficiency.",
    "generateEnergyReport": "Generate a report on energy consumption and management.",
    "generateMAStrategyReport": "Generate a report on the strategy and objectives of mergers and acquisitions.",
    "generateAuditTrailReport": "Generate a detailed audit trail report for tracking changes.",
    "generateFeedbackReport": "Generate a report analyzing customer feedback data.",
    "generateSustainabilityReport": "Generate a report on sustainability initiatives and their impact.",
    "sendItemsByEmail": "Send selected items via email to relevant parties.",
    "exportItems": "Export selected items to an external file format.",
    "importItems": "Import items from an external file format."
};
